# k8s/secrets/secret-provider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: otel-demo
spec:
  provider: azure
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: db-password
          key: db-password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "4ce4a5b4-d6bc-40ee-93c2-883bd2805c6f"
    keyvaultName: "kv-devops-aks-ee128e"
    tenantId: "5581c9a8-168b-45f0-abd4-d375da99bf9f"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""