apiVersion: v1
kind: ResourceQuota
metadata:
  name: otel-demo-quota
  namespace: otel-demo
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "24"
    limits.memory: 40Gi
    pods: "140"
